version: '3.8'

services:
  web:
    build: .
    image: ashuflask:webappv1 
    #command: [" ping", "fb.com"]
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: testdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ashudbc1 
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: