apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tarv-web
  name: tarv-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarv-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tarv-web
    spec:
      containers:
      - image: tarvinder7/tarvtestapp:appvb7994eb1ace3b2823b6ee7c7fd8dcd7a18572bd8
        name: tarvtestapp
        ports:
        - containerPort: 5000
        resources: {}
status: {}
