apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashulb3
  name: ashulb3
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ashu-web
  type: ClusterIP
status:
  loadBalancer: {}
